# Bandit Security Scanner Configuration
# https://bandit.readthedocs.io/

exclude_dirs:
  - /tests/
  - /migrations/
  - /.venv/
  - /node_modules/
  - /__pycache__/

# Ignore specific test IDs (if needed)
skips:
  - B101  # assert_used (allowed in tests)
  - B601  # paramiko_calls (if using SSH legitimately)

# Tests to run (all by default)
tests:
  - B201  # Flask debug mode
  - B301  # Pickle usage
  - B302  # Deserialization
  - B303  # MD5/SHA1 usage
  - B304  # Insecure ciphers
  - B305  # Insecure cipher modes
  - B306  # TempFile.mktemp
  - B307  # eval usage
  - B308  # mark_safe usage
  - B309  # HTTPSConnection
  - B310  # urllib.urlopen
  - B311  # Random for crypto
  - B312  # telnetlib usage
  - B313  # xml.etree
  - B314  # xml.sax
  - B315  # xml.expat
  - B316  # xml.dom.minidom
  - B317  # xml.dom.pulldom
  - B318  # defusedxml
  - B319  # xml.etree.ElementTree
  - B320  # lxml
  - B321  # ftplib
  - B323  # unverified SSL context
  - B324  # hashlib MD5/SHA1
  - B401  # import_telnetlib
  - B402  # import_ftplib
  - B403  # import_pickle
  - B404  # import_subprocess
  - B405  # import_xml_etree
  - B406  # import_xml_sax
  - B407  # import_xml_expat
  - B408  # import_xml_minidom
  - B409  # import_xml_pulldom
  - B410  # import_lxml
  - B411  # import_xmlrpc
  - B412  # import_httpoxy
  - B413  # import_pycrypto
  - B501  # request_with_no_cert_validation
  - B502  # ssl_with_bad_version
  - B503  # ssl_with_bad_defaults
  - B504  # ssl_with_no_version
  - B505  # weak_cryptographic_key
  - B506  # yaml_load
  - B507  # ssh_no_host_key_verification
  - B601  # paramiko_calls
  - B602  # shell_injection
  - B603  # subprocess_without_shell_equals_true
  - B604  # any_other_function_with_shell_equals_true
  - B605  # start_process_with_a_shell
  - B606  # start_process_with_no_shell
  - B607  # start_process_with_partial_path
  - B608  # hardcoded_sql_expressions
  - B609  # linux_commands_wildcard_injection
  - B610  # django_extra_used
  - B611  # django_rawsql_used
  - B701  # jinja2_autoescape_false
  - B702  # use_of_mako_templates
  - B703  # django_mark_safe

# Severity levels
severity:
  - low
  - medium
  - high

# Confidence levels
confidence:
  - low
  - medium
  - high
