"""
ReportGenerator Component
Formats agent outputs into reports
"""
import sys
from typing import Dict, Any, Optional
from pathlib import Path
import json
from datetime import datetime

# Add backend to path
backend_path = Path(__file__).parent.parent.parent
if str(backend_path) not in sys.path:
    sys.path.insert(0, str(backend_path))

from components.base import BaseComponent


class ReportGenerator(BaseComponent):
    """Generate formatted reports from agent data"""
    
    def __init__(self, config: Optional[Dict[str, Any]] = None, mock_mode: bool = False):
        super().__init__(config, mock_mode)
        self.format = self.config.get('format', 'markdown')  # markdown, json, html
        self.template = self.config.get('template', 'default')
        self.include_sections = self.config.get('include_sections', ['all'])
    
    def validate_config(self) -> bool:
        """Validate report configuration"""
        valid_formats = ['markdown', 'json', 'html']
        if self.format not in valid_formats:
            return False
        return True
    
    async def execute(self, data: Dict[str, Any], title: str = "Agent Report") -> Dict[str, Any]:
        """
        Generate report from data
        
        Args:
            data: Report data
            title: Report title
            
        Returns:
            Dict with formatted report
        """
        if not self.validate_config():
            raise ValueError(f"Invalid format: {self.format}")
        
        if self.format == 'markdown':
            content = self._generate_markdown(data, title)
        elif self.format == 'json':
            content = self._generate_json(data, title)
        elif self.format == 'html':
            content = self._generate_html(data, title)
        else:
            content = str(data)
        
        return {
            'content': content,
            'format': self.format,
            'title': title,
            'generated_at': datetime.utcnow().isoformat(),
            'sections': self.include_sections
        }
    
    def _generate_markdown(self, data: Dict[str, Any], title: str) -> str:
        """Generate Markdown report"""
        md = f"# {title}\n\n"
        md += f"**Generated:** {datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S UTC')}\n\n"
        md += "---\n\n"
        
        # Executive Summary
        if 'executive_summary' in self.include_sections or 'all' in self.include_sections:
            md += "## Executive Summary\n\n"
            if 'summary' in data:
                md += f"{data['summary']}\n\n"
        
        # Critical Issues
        if 'critical_issues' in self.include_sections or 'all' in self.include_sections:
            md += "## Critical Issues\n\n"
            if 'issues' in data:
                for i, issue in enumerate(data['issues'], 1):
                    md += f"{i}. **{issue.get('title', 'Issue')}**\n"
                    md += f"   - Severity: {issue.get('severity', 'Unknown')}\n"
                    md += f"   - Description: {issue.get('description', 'N/A')}\n\n"
        
        # Analysis Results
        if 'analysis' in data:
            md += "## Analysis Results\n\n"
            md += f"{data['analysis']}\n\n"
        
        # Recommendations
        if 'recommendations' in self.include_sections or 'all' in self.include_sections:
            md += "## Recommendations\n\n"
            if 'recommendations' in data:
                for i, rec in enumerate(data['recommendations'], 1):
                    md += f"{i}. {rec}\n"
                md += "\n"
        
        # Detailed Data
        if 'detailed_data' in data:
            md += "## Detailed Data\n\n"
            md += "```json\n"
            md += json.dumps(data['detailed_data'], indent=2)
            md += "\n```\n\n"
        
        # Metrics
        if 'metrics' in data:
            md += "## Metrics\n\n"
            for key, value in data['metrics'].items():
                md += f"- **{key}:** {value}\n"
            md += "\n"
        
        md += "---\n\n"
        md += "*Report generated by TeamAI Agent System*\n"
        
        return md
    
    def _generate_json(self, data: Dict[str, Any], title: str) -> str:
        """Generate JSON report"""
        report = {
            'title': title,
            'generated_at': datetime.utcnow().isoformat(),
            'data': data
        }
        return json.dumps(report, indent=2)
    
    def _generate_html(self, data: Dict[str, Any], title: str) -> str:
        """Generate HTML report"""
        html = f"""<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>{title}</title>
    <style>
        body {{ font-family: Arial, sans-serif; max-width: 900px; margin: 0 auto; padding: 20px; }}
        h1 {{ color: #333; }}
        h2 {{ color: #666; border-bottom: 2px solid #ddd; padding-bottom: 10px; }}
        .metric {{ display: inline-block; margin: 10px; padding: 10px; background: #f5f5f5; border-radius: 5px; }}
        .issue {{ background: #fff3cd; padding: 10px; margin: 10px 0; border-left: 4px solid #ffc107; }}
        .timestamp {{ color: #888; font-size: 0.9em; }}
    </style>
</head>
<body>
    <h1>{title}</h1>
    <p class="timestamp">Generated: {datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S UTC')}</p>
    <hr>
"""
        
        # Add content sections
        if 'summary' in data:
            html += f"<h2>Executive Summary</h2><p>{data['summary']}</p>"
        
        if 'issues' in data:
            html += "<h2>Critical Issues</h2>"
            for issue in data['issues']:
                html += f'<div class="issue"><strong>{issue.get("title", "Issue")}</strong><br>'
                html += f'Severity: {issue.get("severity", "Unknown")}<br>'
                html += f'{issue.get("description", "N/A")}</div>'
        
        if 'analysis' in data:
            html += f"<h2>Analysis</h2><pre>{data['analysis']}</pre>"
        
        if 'metrics' in data:
            html += "<h2>Metrics</h2>"
            for key, value in data['metrics'].items():
                html += f'<div class="metric"><strong>{key}:</strong> {value}</div>'
        
        html += """
    <hr>
    <p style="text-align: center; color: #888;">Report generated by TeamAI Agent System</p>
</body>
</html>
"""
        return html
